/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.n0n1.immersive.mode;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;


@Kroll.module(name="ImmersiveMode", id="com.n0n1.immersive.mode")
public class ImmersiveModeModule extends KrollModule
{

	// Standard Debugging variables
	private static final String LCAT = "ImmersiveModeModule";
	private static final String DBG = "ImmersiveModeModule";
	@Kroll.constant public static String VERSION = "1.0";


	public ImmersiveModeModule()
	{
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
		Log.d(DBG, "[onAppCreate]");
		Log.d(LCAT, "Init module: " +  "Immersive Mode " + VERSION);
	}

}

